---
- name: Prepare basic env for php apps on all nodes
  hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - variables.yml
  roles:
    - tools
    - php
    - java
    - selenium
    - xvfb
    