---
- name: Prepare basic env for php apps on all nodes
  hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - variables.yml
  handlers:
    - name: restart selenium
      command: "service selenium stop && sleep 2 && service selenium start"
  roles:
    - tools
    - php
    - java
    - selenium
    - xvfb
    