--- 
- name: Updates apt cache
  action: apt update_cache=true
  become: yes

- name: Install common tools
  apt: name={{ item }} state=latest
  with_items:
    - git-core
    - vim
    - curl
    - mc
    - acl
    - git
    - libxml2-utils
    - graphviz
    - imagemagick
    - libmagickwand-dev
    - htop
    - fish
